#!/bin/bash
#
# file: pull_medalists
#
# description: downloads 
#
# usage: ./pull_medalists <medalists.tsv>
#
# requirements: wget
#
# author: jake hofman (gmail: jhofman)
#

if [ $# -lt 1 ]
then
    echo "usage: ./pull_medalists <medalists.tsv>"
    exit 1
else
    file=$1
fi

for url in `cut -f7 $file | sort | uniq | grep -v '^$'`
do 
    file=`echo $url | sed 's_^http://__'`
    [ -f $file ] || wget -mkr -l 1 -np $url
    # sleep 1
done
